apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: website-helm
  name: {{ .Release.Name }}-website-helm-dev
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: website-helm
  template:
    metadata:
      labels:
        app: website-helm
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: {{ .Values.image.name }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-website-helm-dev-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: website-helm
  type: LoadBalancer